version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: uniti-model-service
    ports:
      - "8000:8000"
    volumes:
      - ./:/app

  # caddy:
  #   image: caddy:2-alpine
  #   depends_on:
  #     - app
  #   ports:
  #     - "80:80"
  #     - "443:443"
